name: cmake-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        PRESET: [ Release, Debug, SanCheck ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependecies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-20 clang++-20

    - name: Configure
      run: |
        cmake . --preset=${{matrix.PRESET}}

    - name: Build
      run: cmake --build . --preset=${{matrix.PRESET}}

    - name: Test
      run: ctest . --preset=${{matrix.PRESET}}